user can vote for the question / answer they like(use json, Concerns)
KhIgorLe/qna pull request #8
Opened 2019-04-03 21:43 UTC by KhIgorLe

2019-04-04 05:35 UTC, sanyco86 commented on app/models/concerns/voteable.rb
> +    if user_voted?(user) && !user.author_of?(self)
проверка на то что пользователь не автор лишняя

2019-04-04 05:35 UTC, sanyco86 commented on app/models/concerns/voteable.rb
> +    unless user_voted?(user) || user.author_of?(self)
для up и down абсолютно одинаковые условия, вынеси проверку в отдельный метод

2019-04-04 05:35 UTC, sanyco86 commented on spec/support/concerns/controllers/vote.rb
> +        expect(response.body).to eq "{\"rating\":1,\"id\":#{resource.id},\"klass\":\"#{resource.class.to_s}\"}"
resource.class.to_s есть метод class_name он вернет название класса, старайся использовать его если тебе нужна строка с названием

2019-04-04 05:35 UTC, sanyco86 commented on spec/support/concerns/models/voteable.rb
> +      resource.down_rating(users[4])
можно в две строки записать
(0..2).each {|i| recource.up_rating users[i]}
(3..4).each {|i| recource.down_rating users[i]}

в принципе можно и в одну итерацию сделать

2019-04-04 05:35 UTC, sanyco86 commented on app/helpers/questions_helper.rb
> +  def link_to_un_rating(question, current_user)
ты нигде не используешь хелпер

2019-04-04 07:45 UTC, vkurennov requested changes

2019-04-04 07:45 UTC, vkurennov commented on app/models/concerns/voteable.rb
> +    unless user_voted?(user) || user.author_of?(self)
Не стоит использовать составные условия в unless, это всегда сложнее читается. Лучше записывать через if и с отрицанием, так условие становится абсолютно понятным.

2019-04-04 07:45 UTC, vkurennov commented on app/models/concerns/voteable.rb
> +      vote = votes.new(rating: 1, user: user)
Используй create, к чему разносить на new + save?

2019-04-04 07:45 UTC, vkurennov commented on app/models/concerns/voteable.rb
> +    unless user_voted?(user) || user.author_of?(self)
Я бы доавбил, что тут вообще оба метода одинаковые и отличаются только знаком аргумента, а значит, можно вынести все это в приватный метод и вызывать из публичных, передавая значение голоса и юзера как параметры.

2019-04-04 07:45 UTC, vkurennov commented on app/models/concerns/voteable.rb
> +    if user_voted?(user) && !user.author_of?(self)
Да, достаточно проверить, что юзер голосовал за этот объект, раз голосовал, значит может и отменить свой голос.

2019-04-04 07:45 UTC, vkurennov commented on app/models/user.rb
> +    resource.user == self
И зачем ты исправил здесь? У тебя же мгновенно появилась проблема N+1 запроса, т.к. теперь на каждый вызов ты делаешь запрос к базе и тянешь оттуда в память ассоциацию user. А ведь достаточно сравнить id.

2019-04-04 07:45 UTC, vkurennov commented on app/models/vote.rb
> +  validates_inclusion_of :rating, in: (-1..1)
используй всегда новый формат валидаций `validates ..., inclusion: { ... }`

2019-04-05 00:01 UTC, KhIgorLe commented on spec/support/concerns/controllers/vote.rb
> +        expect(response.body).to eq "{\"rating\":1,\"id\":#{resource.id},\"klass\":\"#{resource.class.to_s}\"}"
я попытался использовать метод class_name, но  Rspec говорит, что такого метода у него нет.

2019-04-05 07:00 UTC, vkurennov approved these changes

2019-04-06 08:20 UTC, merged

2019-04-07 10:55 UTC, sanyco86 commented on spec/support/concerns/controllers/vote.rb
> +        expect(response.body).to eq "{\"rating\":1,\"id\":#{resource.id},\"klass\":\"#{resource.class.to_s}\"}"
потому, что не стоило погуглись и ты бы понял, что я опечатался и на самом деле не class_name, а class.name

`resource.class.name` но это по сути не принципиально, просто выглядит немного читабельнее